# Generated by Django 4.1.7 on 2023-02-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BulkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BulkProduction_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates', models.ImageField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='CostingandPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostingandPlacement_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GarmentTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GarmentTesting_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='makeadiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makeadiff_quote', models.TextField(blank=True, null=True)),
                ('makeadiff_paragraph', models.TextField(blank=True, null=True)),
                ('organization_if_any', models.ImageField(blank=True, null=True, upload_to='organization_if_any/')),
            ],
        ),
        migrations.CreateModel(
            name='PrintandEmbroidery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrintandEmbroidery_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_development_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Kids', 'Kids'), ('Women', 'Women'), ('Men', 'Men')], max_length=200)),
                ('products_img', models.ImageField(default=None, max_length=250, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='QualityAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QualityAssurance_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrimSourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrimSourcing_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='whypakistan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whypakistan_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='whywe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whywe_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
