# Generated by Django 4.1.7 on 2023-02-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='products_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
