# Generated by Django 4.1.7 on 2023-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_products_products_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='apparelproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostingandPlacement_paragraph', models.TextField(blank=True, null=True)),
                ('CostingandPlacement', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('TrimSourcing', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('TrimSourcing_paragraph', models.TextField(blank=True, null=True)),
                ('BulkProduction', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('BulkProduction_paragraph', models.TextField(blank=True, null=True)),
                ('PrintandEmbroidery_paragraph', models.TextField(blank=True, null=True)),
                ('PrintandEmbroidery', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('QualityAssurance_paragraph', models.TextField(blank=True, null=True)),
                ('QualityAssurance', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('GarmentTesting_paragraph', models.TextField(blank=True, null=True)),
                ('GarmentTesting', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='packagingandshipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_paragraph', models.TextField(blank=True, null=True)),
                ('shipping_paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='sampling',
            new_name='sustainablefashion',
        ),
        migrations.DeleteModel(
            name='BulkProduction',
        ),
        migrations.DeleteModel(
            name='CostingandPlacement',
        ),
        migrations.DeleteModel(
            name='GarmentTesting',
        ),
        migrations.DeleteModel(
            name='PrintandEmbroidery',
        ),
        migrations.DeleteModel(
            name='QualityAssurance',
        ),
        migrations.DeleteModel(
            name='TrimSourcing',
        ),
        migrations.RenameField(
            model_name='sustainablefashion',
            old_name='sampling_paragraph',
            new_name='sustainablefashion_paragraph',
        ),
        migrations.AddField(
            model_name='product_development',
            name='product_development',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product_development',
            name='sampling',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product_development',
            name='sampling_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
