# Generated by Django 4.1.7 on 2023-03-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_apparelproduction_packagingandshipping_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='makeadiff',
        ),
        migrations.DeleteModel(
            name='whypakistan',
        ),
        migrations.AddField(
            model_name='whywe',
            name='makeadiff_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whywe',
            name='makeadiff_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whywe',
            name='organization_if_any',
            field=models.ImageField(blank=True, null=True, upload_to='organization_if_any/'),
        ),
        migrations.AddField(
            model_name='whywe',
            name='whypakistan_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whywe',
            name='whywe_img',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='whywe',
            name='whywepakistan',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='media/'),
        ),
    ]
