# Generated by Django 4.1.7 on 2023-03-06 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_whywe_makeadiff_quote_whywe_makeadiff_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whywe',
            old_name='whywepakistan',
            new_name='whypakistan_img',
        ),
    ]
