# Generated by Django 4.1.7 on 2023-03-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_whywepakistan_whywe_whypakistan_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparelproduction',
            name='BulkProduction',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apparelproduction',
            name='CostingandPlacement',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apparelproduction',
            name='GarmentTesting',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apparelproduction',
            name='PrintandEmbroidery',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apparelproduction',
            name='QualityAssurance',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='apparelproduction',
            name='TrimSourcing',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
    ]
