# Generated by Django 4.1.7 on 2023-03-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_apparelproduction_bulkproduction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apparelproduction',
            new_name='apparelproductions',
        ),
    ]
