# Generated by Django 4.1.7 on 2023-03-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_certificates_certificates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='factoriess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.TextField(blank=True, null=True)),
                ('factory_description', models.TextField(blank=True, null=True)),
                ('factory_date_whenstarted', models.TextField(blank=True, null=True)),
                ('factory_link', models.TextField(blank=True, null=True)),
                ('factory_images', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
