# Generated by Django 4.1.7 on 2023-03-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_factoriess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factoriess',
            old_name='factory_link',
            new_name='factory_owner',
        ),
    ]
