# Generated by Django 4.1.7 on 2023-03-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_factory_link_factoriess_factory_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='delay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factoriess',
            name='delay',
            field=models.IntegerField(blank=True, default='150', null=True),
        ),
    ]
