# Generated by Django 4.1.7 on 2023-03-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_certificates_delay_factoriess_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='delay',
            field=models.IntegerField(blank=True, default='150', null=True),
        ),
    ]
