# Generated by Django 4.1.7 on 2023-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='delay',
            field=models.IntegerField(blank=True, default='150', null=True),
        ),
    ]
