# Generated by Django 4.1.7 on 2023-03-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_services_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='certificate_from',
        ),
    ]
