# Generated by Django 4.1.7 on 2023-03-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_certificates_certificate_from'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apparelproductions',
        ),
        migrations.DeleteModel(
            name='factoriess',
        ),
        migrations.DeleteModel(
            name='packagingandsampling',
        ),
        migrations.DeleteModel(
            name='product_development',
        ),
        migrations.DeleteModel(
            name='shipping',
        ),
    ]
