# Generated by Django 4.1.7 on 2023-03-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_delete_apparelproductions_delete_factoriess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='products/'),
        ),
    ]
