# Generated by Django 4.1.7 on 2023-03-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_products_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Kids Apparel', 'Kids Apparel'), ('Women Apparel', 'Women Apparel'), ('Men Apparel', 'Men Apparel')], max_length=200),
        ),
    ]
