# Generated by Django 4.1.7 on 2023-03-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_img',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
