# Generated by Django 4.1.7 on 2023-03-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_products_products_img_alter_products_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='products_img',
            new_name='products_img1',
        ),
        migrations.AddField(
            model_name='products',
            name='products_img10',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img11',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img12',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img13',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img14',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img15',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img16',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img17',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img18',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img19',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img2',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img20',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img21',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img22',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img23',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img24',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img25',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img26',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img27',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img28',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img29',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img3',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img30',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img4',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img5',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img6',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img7',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img8',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_img9',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
